---
- name: Setup SSH keys and clone GitHub repo
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure required packages are installed
      pacman:
        name:
          - openssh
          - git
          - stow
        state: present

    - name: Generate SSH key
      ansible.builtin.openssh_keypair:
        path: /home/{{ ansible_user_id }}/.ssh/id_rsa
        type: rsa
        size: 4096
      register: ssh_key

    - name: Ensure .ssh directory has correct permissions
      file:
        path: /home/{{ ansible_user_id }}/.ssh
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0700'

    - name: Ensure SSH private key has correct permissions
      file:
        path: /home/{{ ansible_user_id }}/.ssh/id_rsa
        state: file
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0600'

    - name: Ensure SSH public key has correct permissions
      file:
        path: /home/{{ ansible_user_id }}/.ssh/id_rsa.pub
        state: file
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Add SSH key to GitHub (requires GitHub token)
      uri:
        url: https://api.github.com/user/keys
        method: POST
        headers:
          Authorization: "token {{ github_token }}"
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "title": "Ansible-generated key",
            "key": "{{ ssh_key.public_key }}"
          }
      register: github_response

    - name: Check if SSH key was added successfully
      debug:
        msg: "SSH key added successfully"
      when: github_response.status == 201

    - name: Clone the GitHub repository
      git:
        repo: "git@github.com:{{ github_username }}/{{ repo_name }}.git"
        dest: /home/{{ ansible_user_id }}/{{ repo_name }}
        key_file: /home/{{ ansible_user_id }}/.ssh/id_rsa
      vars:
        github_username: "abbesm0hamed"
        repo_name: "dofs"

    - name: Stow the repository
      command: "stow -t /home/{{ ansible_user_id }} {{ repo_name }}"
      args:
        chdir: /home/{{ ansible_user_id }}/{{ repo_name }}
      environment:
        HOME: /home/{{ ansible_user_id }}

