---
- name: Install software on Arch Linux
  hosts: localhost
  become: yes

  tasks:
    - name: Install essential packages
      block:
        - name: Install essential packages from official repositories
          command: "yay -S --noconfirm {{ item }}"
          with_items:
            - base-devel
            - git
            - nodejs
            - npm
            - zsh
          ignore_errors: yes

    - name: Install development tools
      block:
        - name: Install development tools from official repositories
          command: "yay -S --noconfirm {{ item }}"
          with_items:
            - stow
            - arandr
            - wezterm
            - neofetch
            - tmux
            - lazygit
            - fzf
            - ripgrep
            - docker
            - github-cli
            - bat
            - tldr
            - zoxide
            - lsd
            - ranger
            - neovim
            - alacritty
            - mpv
            - ncdu
            - keepassxc
            - btop
            - calibre
            - vlc
            - inkscape
          ignore_errors: yes

    - name: Install AUR packages
      block:
        - name: Install AUR packages
          command: "yay -S --noconfirm {{ item }}"
          with_items:
            - brave-bin
            - cava
            - fastfetch
            - tpm
            - tmuxifier
            - nvm
            - postman-bin
            - virtualbox
            - visual-studio-code-bin
            - the_silver_searcher
            - exa
            - fd
            - espanso
            - conky
            - picom-jonaburg-git
          ignore_errors: yes

    - name: Install fonts and appearance tools
      block:
        - name: Install fonts and appearance tools from official repositories
          command: "yay -S --noconfirm {{ item }}"
          with_items:
            - nerd-fonts
            - rofi
            - polybar
            - feh
            - flameshot
            - dunst
            - kvantum
            - redshift
            - xcolor
          ignore_errors: yes

    - name: Install network and communication tools
      block:
        - name: Install network and communication tools from official repositories
          command: "yay -S --noconfirm {{ item }}"
          with_items:
            - discord
            - telegram-desktop
            - whatsapp-nativefier
            - slack-desktop
            - zoom
            - teams
            - anydesk
          ignore_errors: yes

    - name: Install media and utility tools
      block:
        - name: Install media and utility tools from official repositories
          command: "yay -S --noconfirm {{ item }}"
          with_items:
            - gimp
            - cheese
            - audacity
            - docker-compose
            - ufw
            - clamav
          ignore_errors: yes

        - name: Enable Docker service
          systemd:
            name: docker
            enabled: yes
            state: started

    - name: Shell configuration and customization
      block:
        - name: Install zinit
          shell: |
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/scripts/install.sh)"
          args:
            creates: /home/{{ ansible_user_id }}/.zinit/bin/zinit.zsh
          become: false

        - name: Change default shell to Zsh
          command: "chsh -s /usr/bin/zsh"
          become_user: "{{ ansible_user_id }}"

        - name: Verify Zsh is the default shell
          command: "echo $SHELL"
          register: shell_check
          changed_when: "shell_check.stdout != '/usr/bin/zsh'"

        - name: Print message about Zsh default shell change
          debug:
            msg: "Please log out and log back in to use Zsh as your default shell."

        - name: Install TPM (Tmux Plugin Manager)
          git:
            repo: https://github.com/tmux-plugins/tpm
            dest: /home/{{ ansible_user_id }}/.tmux/plugins/tpm
            version: master
          become: false
