---
- name: Install software on Arch Linux
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure base-devel and other essential dependencies are installed
      pacman:
        name:
          - base-devel
          - git
          - nodejs
          - npm
          - zsh
        state: present

    - name: Install Yay AUR Helper
      shell: |
        pacman -S --needed git base-devel
        git clone https://aur.archlinux.org/yay.git /tmp/yay
        cd /tmp/yay
        makepkg -si --noconfirm
      args:
        chdir: /tmp
      register: yay_installed
      changed_when: "'yay' not in ansible_facts.packages"

- name: Install Development Tools
  hosts: localhost
  become: yes
  tasks:
    - name: Install development tools from official repositories
      pacman:
        name:
          - stow
          - arandr
          - wezterm
          - neofetch
          - tmux
          - nodejs
          - npm
          - lazygit
          - docker
          - github-cli
          - bat
          - tldr
          - zoxide
          - lsd
          - ranger
          - neovim
          - alacritty
          - mpv
          - ncdu
          - keepassxc
          # - libreoffice-fresh
          - btop
          - calibre
          - vlc
          - inkscape
          # - blender
        state: present

    - name: Install development tools from AUR using Yay
      command: "yay -S --noconfirm {{ item }}"
      with_items:
        - brave-bin
        - cava
        - fastfetch
        - tpm
        - tmuxifier
        - nvm
        - postman-bin
        - virtualbox
        - code-bin
        - the_silver_searcher
        - exa
        - fd
      when: yay_installed.changed

- name: Install Fonts and Appearance Tools
  hosts: localhost
  become: yes
  tasks:
    - name: Install fonts and appearance tools from official repositories
      pacman:
        name:
          - nerd-fonts
          - rofi
          - polybar
          - feh
          - flameshot
          - dunst
          - kvantum
          - redshift
          - xcolor
        state: present

    - name: Install fonts and appearance tools from AUR using Yay
      command: "yay -S --noconfirm {{ item }}"
      with_items:
        - espanso
        - conky
        - picom-jonaburg-git
      when: yay_installed.changed

- name: Install Network and Communication Tools
  hosts: localhost
  become: yes
  tasks:
    - name: Install network and communication tools from official repositories
      pacman:
        name:
          - discord
          - telegram-desktop
          - slack-desktop
          - zoom
          - teams
          - anydesk
        state: present

    - name: Install network and communication tools from AUR using Yay
      command: "yay -S --noconfirm {{ item }}"
      with_items:
        - whatsapp-nativefier
      when: yay_installed.changed

- name: Install Media and Utility Tools
  hosts: localhost
  become: yes
  tasks:
    - name: Install media and utility tools from official repositories
      pacman:
        name:
          - gimp
          - cheese
          - audacity
          - docker-compose
          - ufw
          - clamav
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

- name: Shell Configuration and Customization
  hosts: localhost
  become: yes
  tasks:
    - name: Install zinit
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/scripts/install.sh)"
      args:
        creates: /home/{{ ansible_user_id }}/.zinit/bin/zinit.zsh
      become: false

    - name: Change default shell to Zsh
      command: "chsh -s /usr/bin/zsh"
      become_user: "{{ ansible_user_id }}"

    - name: Verify Zsh is the default shell
      command: "echo $SHELL"
      register: shell_check
      changed_when: "shell_check.stdout != '/usr/bin/zsh'"

    - name: Print message about Zsh default shell change
      debug:
        msg: "Please log out and log back in to use Zsh as your default shell."

    - name: Install TPM (Tmux Plugin Manager)
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/{{ ansible_user_id }}/.tmux/plugins/tpm
        version: master
      become: false
